title: Nurida Karimbaeva
url: "http://nuridak.github.io"
baseurl: "/Resume"

markdown: kramdown

remote_theme: ankitsultana/researcher@gem

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/Resume/"
 - name: "Resume"
   link: "resume.pdf"
